name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm trying to do X but currently have to Y...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        ```python
        # Example of how the new feature might look
        client.agents.new_method(...)
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which part of the SDK does this affect?
      options:
        - Agents resource
        - Search resource
        - Users resource
        - Reviews resource
        - Categories resource
        - Analytics resource
        - Authentication
        - Configuration
        - Async client
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
